[workspace]
members = [
  "fawkes-crypto",
  "fawkes-crypto_derive",
  "ff-uint",
  "ff-uint_derive",
  "seedbox"
]

[patch."https://github.com/privacy-scaling-explorations/poseidon.git"]
poseidon = { git = "https://github.com/gnull/poseidon", branch = "patch-1" }